site_name: Circuito de Gestão
docs_dir: base
site_dir: docs
site_url: https://instituto-unibanco.github.io/cdg

nav:
  - Apresentação: index.md

theme:
  name: material
  palette:
    primary: custom
  language: pt-BR
  features:
    - navigation.tabs
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: logo

# repo_url: https://www.institutounibanco.org.br
# repo_name: Instituto Unibanco

extra_css:
  - stylesheets/extra.css

plugins:
  - social
  - search
