name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install the project dependencies
        run: |
          rm -f poetry.lock
          poetry install
      - name: Build Docs
        run: |
          sh ./build_all.sh
          git status
      - name: Publish Docs
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          add: 'docs'
          tag_push: '--force'
          new_branch: built
    
